export const products = [
  {
    id: "1",
    title: "Lavender",
    rate: 4.5,
    numOfRatings: 120,
    scientificName: "Lavandula angustifolia",
    commonNames: ["English Lavender", "True Lavender"],
    description:
      "Lavender is a popular aromatic herb known for its fragrant purple flowers and soothing properties.",
    mainImg: "/assests/img/shop/shop1.jpg",
    otherViews: [
      "/assests/img/shop/shop1.jpg",
      "/assests/img/shop/shop2.jpg",
      "/assests/img/shop/shop3.jpg",
    ],
    price: 12.99,
  },
  {
    id: "2",
    title: "Rosemary",
    rate: 4.3,
    numOfRatings: 98,
    scientificName: "Rosmarinus officinalis",
    commonNames: ["Dew of the Sea", "Rosemary Bush"],
    description:
      "Rosemary is a woody herb with needle-like leaves, often used in cooking and for its pleasant scent.",
    mainImg: "/assests/img/shop/shop2.jpg",
    otherViews: [
      "/assests/img/shop/shop1.jpg",
      "/assests/img/shop/shop2.jpg",
      "/assests/img/shop/shop3.jpg",
    ],
    price: 9.99,
  },
  {
    id: "3",
    title: "Sunflower",
    rate: 4.8,
    numOfRatings: 215,
    scientificName: "Helianthus annuus",
    commonNames: ["Common Sunflower"],
    description:
      "The sunflower is known for its large, yellow flowers and edible seeds.",
    mainImg: "/assests/img/shop/shop3.jpg",
    otherViews: [
      "/assests/img/shop/shop1.jpg",
      "/assests/img/shop/shop2.jpg",
      "/assests/img/shop/shop3.jpg",
    ],
    price: 6.99,
  },
  {
    id: "4",
    title: "Tulip",
    rate: 4.0,
    numOfRatings: 65,
    scientificName: "Tulipa",
    commonNames: ["Garden Tulip"],
    description:
      "Tulips are colorful spring-blooming flowers that come in various shapes and sizes.",
    mainImg: "/assests/img/shop/shop1.jpg",
    otherViews: [
      "/assests/img/shop/shop4.jpg",
      "/assests/img/shop/shop5.jpg",
      "/assests/img/shop/shop6.jpg",
    ],
    price: 5.49,
  },
  {
    id: "5",
    title: "Aloe Vera",
    rate: 4.6,
    numOfRatings: 150,
    scientificName: "Aloe barbadensis miller",
    commonNames: ["Medicinal Aloe", "Burn Plant"],
    description:
      "Aloe Vera is a succulent plant known for its healing properties, often used for skin conditions.",
    mainImg: "/assests/img/shop/shop2.jpg",
    otherViews: [
      "/assests/img/shop/shop4.jpg",
      "/assests/img/shop/shop5.jpg",
      "/assests/img/shop/shop6.jpg",
    ],
    price: 7.99,
  },
  {
    id: "6",
    title: "Mint",
    rate: 4.4,
    numOfRatings: 110,
    scientificName: "Mentha",
    commonNames: ["Peppermint", "Spearmint"],
    description:
      "Mint is a fragrant herb commonly used in cooking, teas, and for its refreshing flavor.",
    mainImg: "/assests/img/shop/shop3.jpg",
    otherViews: [
      "/assests/img/shop/shop4.jpg",
      "/assests/img/shop/shop5.jpg",
      "/assests/img/shop/shop6.jpg",
    ],
    price: 3.99,
  },
  {
    id: "7",
    title: "Ficus",
    rate: 4.1,
    numOfRatings: 75,
    scientificName: "Ficus benjamina",
    commonNames: ["Weeping Fig", "Benjamin Fig"],
    description:
      "Ficus is a popular indoor plant with glossy leaves, known for its air-purifying qualities.",
    mainImg: "/assests/img/shop/shop2.jpg",
    otherViews: [
      "/assests/img/shop/shop7.jpg",
      "/assests/img/shop/shop8.jpg",
      "/assests/img/shop/shop9.jpg",
    ],
    price: 15.99,
  },
  {
    id: "8",
    title: "Lily of the Valley",
    rate: 4.2,
    numOfRatings: 82,
    scientificName: "Convallaria majalis",
    commonNames: ["May Lily", "Wood Lily"],
    description:
      "Lily of the Valley is a fragrant woodland plant with bell-shaped white flowers.",
    mainImg: "/assests/img/shop/shop1.jpg",
    otherViews: [
      "/assests/img/shop/shop7.jpg",
      "/assests/img/shop/shop8.jpg",
      "/assests/img/shop/shop9.jpg",
    ],
    price: 8.49,
  },
  {
    id: "9",
    title: "Succulent Echeveria",
    rate: 4.7,
    numOfRatings: 185,
    scientificName: "Echeveria",
    commonNames: ["Hens and Chicks", "Hen's Head"],
    description:
      "Succulent Echeveria is a group of small, rosette-forming succulent plants.",
    mainImg: "/assests/img/shop/shop3.jpg",
    otherViews: [
      "/assests/img/shop/shop7.jpg",
      "/assests/img/shop/shop8.jpg",
      "/assests/img/shop/shop9.jpg",
    ],
    price: 10.99,
  },
  {
    id: "10",
    title: "Cactus",
    rate: 4.9,
    numOfRatings: 250,
    scientificName: "Cactaceae",
    commonNames: ["Prickly Pear", "Saguaro"],
    description:
      "Cacti are succulent plants known for their unique shapes, spines, and ability to thrive in arid conditions.",
    mainImg: "/assests/img/shop/shop1.jpg",
    otherViews: [
      "/assests/img/shop/shop10.jpg",
      "/assests/img/shop/shop11.jpg",
      "/assests/img/shop/shop12.jpg",
    ],
    price: 4.99,
  },
  {
    id: "11",
    title: "Orchid",
    rate: 4.2,
    numOfRatings: 95,
    scientificName: "Orchidaceae",
    commonNames: ["Phalaenopsis", "Cymbidium"],
    description:
      "Orchids are diverse and beautiful flowering plants, popular in gardens and as indoor houseplants.",
    mainImg: "/assests/img/shop/shop2.jpg",
    otherViews: [
      "/assests/img/shop/shop10.jpg",
      "/assests/img/shop/shop11.jpg",
      "/assests/img/shop/shop12.jpg",
    ],
    price: 12.49,
  },
  {
    id: "12",
    title: "Bamboo",
    rate: 4.5,
    numOfRatings: 120,
    scientificName: "Bambusoideae",
    commonNames: ["Giant Bamboo", "Lucky Bamboo"],
    description:
      "Bamboo is a versatile plant used for construction, furniture, and as an ornamental plant.",
    mainImg: "/assests/img/shop/shop3.jpg",
    otherViews: [
      "/assests/img/shop/shop10.jpg",
      "/assests/img/shop/shop11.jpg",
      "/assests/img/shop/shop12.jpg",
    ],
    price: 11.99,
  },
];

export const comments = [{}];
