import './globals.css'
import type { Metadata } from 'next'
import { Syne } from 'next/font/google'
import Navbar from './components/navbar/Navbar'
import Footer from './components/Footer';


const font = Syne({
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={font.className}>
        <Navbar />
        <div>
          {children}
        </div>
        <Footer />
      </body>
    </html>
  )
}
